controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#Création de mes routes et des controleurs associés
accueil:
  path: /accueil
  controller: App\Controller\HomeController::index

contract_list:
    path: /utilisateurs
    controller: App\Controller\UtilisateurListController::listUtilisateurs

inscription_succes:
    path: '/inscription/success' # Le chemin de ma route pour le message "inscription réusssie"
    controller: 'App\Controller\UtilisateurController::inscriptionSucces' # Le contrôleur et l'action associés à cette route

afficher_produits:
    path: /afficher-produits
    controller: 'App\Controller\ProduitController::afficherProduits'